import { STATUS } from '../constants.js';

/** @typedef {{ module: string, code: string, chapter: number, title: string, criteria: string, precondition: string, status: string }} SeedRow */

/** @type {SeedRow[]} */
export const SEED_TODO = [
  // 第 0 章　App 级冒烟（无数据前提）
  {
    module: 'todo',
    code: '0.1',
    chapter: 0,
    title: '冷启动进主界面，不停在 Welcome',
    criteria: '`czl_nav_bar` 可见 且 `txtGetStarted` 不可见',
    precondition: '无数据前提',
    status: STATUS.PASSED,
  },
  {
    module: 'todo',
    code: '0.2',
    chapter: 0,
    title: '杀进程再进仍是登录态',
    criteria: '同上，且不清数据',
    precondition: '无数据前提',
    status: STATUS.PASSED,
  },
  {
    module: 'todo',
    code: '0.3',
    chapter: 0,
    title: '日视图 / 周视图切换',
    criteria: '日视图统计区 ↔ `tl_2`',
    precondition: '无数据前提',
    status: STATUS.PASSED,
  },
  {
    module: 'todo',
    code: '0.4',
    chapter: 0,
    title: 'Todo 竖屏入口与根页',
    criteria: '底部切到 To-do 后 `rvTodo` 可见',
    precondition: '无数据前提',
    status: STATUS.PASSED,
  },

  // 第 1 章　todo-list（前提：有 list，无 todos；不点 Display / Filter）
  {
    module: 'todo',
    code: '1.1',
    chapter: 1,
    title: '创建 List（名称 + 颜色 + 图标）',
    criteria: '根页出现该卡片；Lists 弹窗内有该行',
    precondition: '有 list，无 todos；不点 Display / Filter',
    status: STATUS.PASSED,
  },
  {
    module: 'todo',
    code: '1.2',
    chapter: 1,
    title: '编辑 List',
    criteria: '编辑弹窗预填旧名（不符即失败，不写数据）；保存后新名可见',
    precondition: '有 list，无 todos；不点 Display / Filter',
    status: STATUS.PASSED,
  },
  {
    module: 'todo',
    code: '1.3',
    chapter: 1,
    title: '改动落库',
    criteria: '杀进程重进，改名仍在',
    precondition: '有 list，无 todos；不点 Display / Filter',
    status: STATUS.PASSED,
  },
  {
    module: 'todo',
    code: '1.4',
    chapter: 1,
    title: '删除 List',
    criteria: '卡片与 Lists 行都消失；整轮只发 1 个 delete 请求',
    precondition: '有 list，无 todos；不点 Display / Filter',
    status: STATUS.PASSED,
  },
  {
    module: 'todo',
    code: '1.5',
    chapter: 1,
    title: '拖拽排序',
    criteria: '手柄拖动后相邻顺序变化；杀进程重进后顺序保持',
    precondition: '有 list，无 todos；不点 Display / Filter',
    status: STATUS.PASSED,
  },
  {
    module: 'todo',
    code: '1.6',
    chapter: 1,
    title: 'List 数量上限',
    criteria: '到 `MAX_TODO_LIST_COUNT` 时出提示、不再新增',
    precondition: '有 list，无 todos；不点 Display / Filter',
    status: STATUS.MANUAL,
  },

  // 第 2 章　单 List 内的 Todo（前提：有 1 个夹具 List；仍不点 Display / Filter）
  {
    module: 'todo',
    code: '2.1',
    chapter: 2,
    title: '卡片内快速添加',
    criteria:
      '含 `tv_todolist_title=E2E Todo` 的卡片内可见 `E2E_Fast`；不得只断言全屏文字',
    precondition: '有 1 个夹具 List；仍不点 Display / Filter',
    status: STATUS.PENDING_WRITE,
  },
  {
    module: 'todo',
    code: '2.2',
    chapter: 2,
    title: '根页 Add 完整创建',
    criteria:
      '保存前确认弹窗选中的是夹具 List，否则失败不保存；出现 `E2E_Full`',
    precondition: '有 1 个夹具 List；仍不点 Display / Filter',
    status: STATUS.PENDING_WRITE,
  },
  {
    module: 'todo',
    code: '2.3',
    chapter: 2,
    title: '编辑改名',
    criteria: '旧名消失、新名可见',
    precondition: '有 1 个夹具 List；仍不点 Display / Filter',
    status: STATUS.PENDING_WRITE,
  },
  {
    module: 'todo',
    code: '2.4',
    chapter: 2,
    title: '删除单条 Todo',
    criteria: '该条消失，夹具 List 仍在',
    precondition: '有 1 个夹具 List；仍不点 Display / Filter',
    status: STATUS.PENDING_WRITE,
  },
  {
    module: 'todo',
    code: '2.5',
    chapter: 2,
    title: 'Todo 落库',
    criteria: '杀进程重进，2.1/2.2 的条目仍在',
    precondition: '有 1 个夹具 List；仍不点 Display / Filter',
    status: STATUS.PENDING_WRITE,
  },

  // 第 3 章　Display 排序（前提：同一 List 内多条 Todo，标题与截止时间可区分）
  {
    module: 'todo',
    code: '3.1',
    chapter: 3,
    title: 'group by List / Profile',
    criteria:
      '**卡片集合变化**（List → 每个 list 一张卡；Profile → 每人一张卡）',
    precondition: '同一 List 内多条 Todo，标题与截止时间可区分',
    status: STATUS.PENDING_WRITE,
  },
  {
    module: 'todo',
    code: '3.2',
    chapter: 3,
    title: 'sort by title',
    criteria: '相邻顺序断言（`above` / `below`）',
    precondition: '同一 List 内多条 Todo，标题与截止时间可区分',
    status: STATUS.PENDING_WRITE,
  },
  {
    module: 'todo',
    code: '3.3',
    chapter: 3,
    title: 'sort by due date',
    criteria: '同上',
    precondition: '同一 List 内多条 Todo，标题与截止时间可区分',
    status: STATUS.PENDING_WRITE,
  },
  {
    module: 'todo',
    code: '3.4',
    chapter: 3,
    title: '配置落库',
    criteria: '杀进程重进，配置仍在',
    precondition: '同一 List 内多条 Todo，标题与截止时间可区分',
    status: STATUS.FALSE_GREEN,
  },

  // 第 4 章　完成态（前提：有已完成的 Todo）
  {
    module: 'todo',
    code: '4.1',
    chapter: 4,
    title: '勾选完成',
    criteria: '该条进入完成态',
    precondition: '有已完成的 Todo',
    status: STATUS.PENDING_WRITE,
  },
  {
    module: 'todo',
    code: '4.2',
    chapter: 4,
    title: 'Show completed 开关',
    criteria: '关闭时完成项不可见、开启时可见',
    precondition: '有已完成的 Todo',
    status: STATUS.PENDING_WRITE,
  },
  {
    module: 'todo',
    code: '4.3',
    chapter: 4,
    title: '反完成',
    criteria: '回到未完成态',
    precondition: '有已完成的 Todo',
    status: STATUS.PENDING_WRITE,
  },

  // 第 5 章　Filter（前提：多成员 + 已指派的 Todo）
  {
    module: 'todo',
    code: '5.1',
    chapter: 5,
    title: '按成员筛选',
    criteria: '只剩该成员的条目',
    precondition: '多成员 + 已指派的 Todo',
    status: STATUS.PENDING_WRITE,
  },
  {
    module: 'todo',
    code: '5.2',
    chapter: 5,
    title: '清除筛选',
    criteria: '恢复全量',
    precondition: '多成员 + 已指派的 Todo',
    status: STATUS.PENDING_WRITE,
  },
];
